[font]

size = 14.0
normal = {family = "FiraCode Nerd Font", style="Regular"}

[window]

startup_mode = "maximized"

[env]
term = "xterm-256color"

[colors]

[general]
import = [
  # uncomment the flavour you want below:
	#"~/.config/alacritty/catppuccin-latte.toml"
	#"~/.config/alacritty/catppuccin-frappe.toml"
	# "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

